In [7]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

In [9]:
df = pd.read_csv('C:\\Users\\HP\\Documents\\diabetes.csv')

In [11]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [13]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [15]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [17]:
#to correct values
df.corr()

Pregnancies   Glucose  BloodPressure  SkinThickness  \
Pregnancies                  1.000000  0.129459       0.141282      -0.081672   
Glucose                      0.129459  1.000000       0.152590       0.057328   
BloodPressure                0.141282  0.152590       1.000000       0.207371   
SkinThickness               -0.081672  0.057328       0.207371       1.000000   
Insulin                     -0.073535  0.331357       0.088933       0.436783   
BMI                          0.017683  0.221071       0.281805       0.392573   
DiabetesPedigreeFunction    -0.033523  0.137337       0.041265       0.183928   
Age                          0.544341  0.263514       0.239528      -0.113970   
Outcome                      0.221898  0.466581       0.065068       0.074752   

                           Insulin       BMI  DiabetesPedigreeFunction  \
Pregnancies              -0.073535  0.017683                 -0.033523   
Glucose                   0.331357  0.221071                  0.137337   
BloodPressure             0.088933  0.281805                  0.041265   
SkinThickness             0.436783  0.392573                  0.183928   
Insulin                   1.000000  0.197859                  0.185071   
BMI                       0.197859  1.000000                  0.140647   
DiabetesPedigreeFunction  0.185071  0.140647                  1.000000   
Age                      -0.042163  0.036242                  0.033561   
Outcome                   0.130548  0.292695                  0.173844   

                               Age   Outcome  
Pregnancies               0.544341  0.221898  
Glucose                   0.263514  0.466581  
BloodPressure             0.239528  0.065068  
SkinThickness            -0.113970  0.074752  
Insulin                  -0.042163  0.130548  
BMI                       0.036242  0.292695  
DiabetesPedigreeFunction  0.033561  0.173844  
Age                       1.000000  0.238356  
Outcome                   0.238356  1.000000

In [19]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [21]:
# splitting into x and y
x= df.drop('Outcome', axis=1)
y= df['Outcome']

In [23]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [25]:
x_train.shape

(614, 8)

In [27]:
x_test.shape

(154, 8)

In [29]:
y_train.shape

(614,)

In [31]:
y_test.shape

(154,)

In [33]:
rfc= RandomForestClassifier()

In [35]:
rfc.fit(x_train, y_train)

RandomForestClassifier()

In [37]:
rfcpred= rfc.predict(x_test)

In [39]:
rfcpred [:10]

array([0, 0, 0, 0, 0, 1, 0, 1, 1, 1], dtype=int64)

In [43]:
rfcaccuracy= accuracy_score(y_test, rfcpred)*100

In [45]:
rfcaccuracy

72.07792207792207

In [47]:
dtc= DecisionTreeClassifier()

In [49]:
dtc.fit(x_train, y_train)

DecisionTreeClassifier()

In [51]:
dtcpred= dtc.predict(x_test)

In [53]:
dtcpred [:10]

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int64)

In [57]:
dtcaccuracy= accuracy_score(y_test, dtcpred)*100

In [59]:
svmmodel= SVC()

In [61]:
svmmodel.fit(x_train, y_train)

SVC()

In [63]:
svmmodelpred= svmmodel.predict(x_test)

In [65]:
svmmodelpred [:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

In [67]:
svmmodelaccuracy= accuracy_score(y_test, svmmodelpred)*100

In [69]:
svmmodelaccuracy

76.62337662337663

In [71]:
naive= GaussianNB()

In [75]:
naive.fit(x_train, y_train)

GaussianNB()

In [77]:
naivepred= naive.predict(x_test)

In [79]:
naivepred [:10]

array([0, 0, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

In [81]:
naiveaccuracy= accuracy_score(y_test, naivepred)*100

In [83]:
naiveaccuracy

76.62337662337663

In [87]:
knn = KNeighborsClassifier()

In [89]:
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [91]:
knnpred= knn.predict(x_test)

In [93]:
knnpred [:10]

array([0, 0, 0, 1, 0, 1, 0, 0, 1, 1], dtype=int64)

In [95]:
knnaccuracy= accuracy_score(y_test, knnpred)*100

In [97]:
knnaccuracy

66.23376623376623